# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DRF Docs

description: Document Web APIs made with Django Rest Framework

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://www.drfdocs.com" # the base hostname & protocol for your site

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

twitter_username: iamemmanouil
github_username:  ekonstantinidis
github_repo_url: ekonstantinidis/drfdocs

available_versions:
  - v0.0.1
  - v0.0.2
  - v0.0.3

# Build settings
markdown: kramdown
exclude: ['node_modules', 'package.json']
